# Path: /fly.toml

app = "ai-voice-agent"
primary_region = "iad"  # or choose closest region

[build]
  image = "python:3.11-slim"

[env]
  OPENAI_API_KEY = "your_openai_key"
  ELEVENLABS_API_KEY = "your_11labs_key"
  SHEET_ID = "your_google_sheet_id"
  GCAL_ID = "your_calendar_id"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 8000
  force_https = true
  auto_start = true
  auto_stop = true
  min_machines_running = 1
  processes = ["app"]
